from pathlib import Path
p=Path(__file__).parent
cats='<nav class="categories" aria-label="カテゴリ"><a href="https://emotionbookstore.com/work-book.html">本</a><a href="https://emotionbookstore.com/work-music.html">音楽</a><a href="https://emotionbookstore.com/work-video.html">映像</a><a href="https://emotionbookstore.com/outings/">展示</a><a href="https://emotionbookstore.com/outings/">ライブ</a></nav>'
header='<header><img src="assets/logo.png" width="1429" height="331" alt="みんなの感情書店"><p>本・音楽・映像・街の催しに出会う文化案内</p></header>'
reading='本屋に入ったら、いつも選ばない棚をひとつだけ眺めてみる。題名の響き、背表紙の色、知らない言葉。気になった一冊を開いて、一行だけ読む。買うかどうかは、そのあとでいい。今日は「気になる」をひとつ見つけたら、それで十分。'
mini=f'<details class="mini" id="reading"><summary><span><small>ひとくち読み物 · 約30秒</small><strong>本を決めずに、本屋へ。</strong></span><span aria-hidden="true">＋</span></summary><p class="read">{reading}</p><p class="byline">感情書店の小文</p></details>'
short=f'<details class="short-note" id="reading"><summary><span class="eyebrow">ひとくち読み物 · 約30秒</span>本を決めずに、<br>本屋へ。<span>ここで読む ＋</span></summary><p class="read">{reading}</p><p class="byline">感情書店の小文</p></details>'
cards='<div class="grid"><a class="card" href="https://emotionbookstore.com/work-book.html"><img src="assets/books.webp" alt="本棚のイメージ写真" width="568" height="426"><div class="caption">イメージ写真</div><p class="meta">本 ／ 神保町</p><h3>森崎書店の日々</h3><p>神保町を舞台にした物語へ。</p><span class="action">この本を知る ↗</span></a><a class="card" href="https://emotionbookstore.com/work-music.html"><img src="assets/music.webp" alt="レコードプレーヤーのイメージ写真" width="1600" height="1067"><div class="caption">イメージ写真</div><p class="meta">音楽 ／ 下北沢</p><h3>不透明度<br>Live at Shelter</h3><p>下北沢で録音された一曲。</p><span class="action">音楽を探す ↗</span></a></div>'
video='<a class="video" href="https://www.youtube.com/watch?v=dt33RGSRuo0" target="_blank" rel="noopener noreferrer"><img src="assets/dance.webp" alt="高円寺の阿波おどりの記録写真" width="1524" height="1016"><div><p><span class="type-tag">映像</span>5分39秒</p><h3>通りが、踊りの舞台になる。</h3><p>高円寺の阿波おどり · 2025年公式映像</p><span class="action">公式映像を見る ↗</span></div></a>'
mood='<details class="mood"><summary>気分から探す</summary><a href="#reading">ちょっと一息</a><a href="https://emotionbookstore.com/work-video.html">何か観たい</a><a href="https://emotionbookstore.com/outings/">外に出たい</a></details>'
for mode,body in [('a','<div class="intro"><h1>今日、何に出会おう。</h1><p>気になる本、一曲、週末の楽しみ。<br>まずは、目に留まったものから。</p></div>'+cats+'<main><div class="heading"><h2>今日の入口</h2><small>本と音楽から</small></div>'+cards+mini+video+mood+'</main>'),('b','<div class="intro"><h1>ひまな時間に、<br>ひとつ発見。</h1><p>読んで、聴いて、気になったら街へ。</p></div>'+cats+'<main>'+short+'<div class="heading"><h2>次は、何を楽しむ？</h2></div>'+cards+video+mood+'</main>')]:
 (p/(mode+'.html')).write_text('<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>感情書店 — '+mode.upper()+'案</title><link rel="stylesheet" href="style.css"></head><body class="'+mode+'">'+header+body+'<footer>感情書店の小文：今回書き下ろした原稿案。<br>写真：既存の出典確認済み素材。踊り写真 Lucertola。<br><a href="https://emotionbookstore.com/credits.html">写真・出典</a> · <a href="assets/shipporimincho-OFL.txt">明朝ライセンス</a> · <a href="assets/zenkakugothicnew-OFL.txt">ゴシックライセンス</a></footer></body></html>')
