'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(root,'release_content.js'),'utf8'),sandbox);
const content=sandbox.window.V3_RELEASE_CONTENT;
const shelf=content.shelves.find(s=>s.id==='kiyosumi');
assert.ok(shelf,'Kiyosumi shelf exists');
assert.equal(content.release.shelfCount,5);
assert.equal(shelf.area,'清澄白河');
assert.equal(shelf.objects.length,3);
assert.deepEqual(Array.from(shelf.objects,o=>o.id),['kiyosumi-garden','fukagawa-edo-museum','mot-collection-light']);
assert.ok(shelf.weeklyFeature && /^https:\/\//.test(shelf.weeklyFeature.actionUrl));
assert.equal(shelf.entryMedia.kind,'photo');
assert.equal(shelf.heroMedia.url,'./assets/city-kiyosumi.jpg');
assert.equal(shelf.heroMedia.source,'Wikimedia Commons');
assert.equal(shelf.heroMedia.license,'CC BY-SA 4.0');
assert.equal(shelf.entryMedia.url,'./assets/city-kiyosumi.jpg');
const home=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(home,/清澄白河/);
assert.match(home,/href="\/discover\/kiyosumi\/"/);
assert.match(home,/\/assets\/city-kiyosumi\.jpg/);
assert.doesNotMatch(home,/upload\.wikimedia\.org[^"']*Kiyosumi/i);
const sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');
assert.match(sitemap,/discover\/kiyosumi\//);
const discovery=fs.readFileSync(path.join(root,'discover/kiyosumi/index.html'),'utf8');
assert.doesNotMatch(discovery,/bLuK6QHKc7E|Rw9IZ2vbWEM/);
assert.match(discovery,/src="\/assets\/city-kiyosumi\.jpg"/);
assert.doesNotMatch(discovery,/upload\.wikimedia\.org/);
assert.match(discovery,/東京都現代美術館/);
const runtime=fs.readFileSync(path.join(root,'release.js'),'utf8');
assert.match(runtime,/syncCityMenuFromContent/);
console.log('PASS Kiyosumi 5th-city contract');
