'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {compose,calendarDates,googleCalendar,calendarFile}=require('../memory-note');
const result=compose('作品名','/discover/koenji/1q84.html?_vercel_share=secret#private','  自分だけの感想  ');
assert.ok(result.includes('https://emotionbookstore.com/discover/koenji/1q84.html'));
assert.ok(result.endsWith('自分だけの感想'));
assert.doesNotMatch(result,/secret|_vercel_share|#private/);
assert.ok(compose('作品','/works.html','',['行ってみたい']).endsWith('行ってみたい'),'Stamp alone is enough');
assert.ok(compose('作品','/works.html','ひとこと',['心に残った','心に残った','任意の値']).endsWith('心に残った\nひとこと'),'Only supported stamps, without duplicates');
const js=fs.readFileSync(require.resolve('../memory-note'),'utf8');
assert.doesNotMatch(js,/fetch\(|localStorage|sessionStorage|gtag|console\./);
const chrome=require('../tools/page-chrome');
const sample='<html><head></head><body><main><article class="detail"></article></main></body></html>';
assert.equal(chrome(chrome(sample)),chrome(sample),'Idempotent generation');
assert.doesNotMatch(chrome('<html><head></head><body><main>一覧</main></body></html>'),/data-memory-note/);
assert.deepEqual(calendarDates('2028-02-29'),['20280229','20280301']);
assert.throws(()=>calendarDates('2026-02-30'));
assert.throws(()=>calendarDates(''));
const gcal=new URL(googleCalendar('作品 & 音楽',result,'2026-12-31'));
assert.equal(gcal.origin,'https://calendar.google.com');
assert.equal(gcal.searchParams.get('dates'),'20261231/20270101');
assert.equal(gcal.searchParams.get('text'),'気になる：作品 & 音楽');
assert.ok(gcal.searchParams.get('details').includes('自分だけの感想'));
assert.doesNotMatch(gcal.href,/secret|_vercel_share/);
const ics=calendarFile('作品\\n改行',compose('作品','/works.html','思い'.repeat(100)+'\r\nBEGIN:VEVENT',['心に残った']),'2026-12-31',new Date('2026-09-08T00:00:00Z'));
assert.equal(ics.split('\r\n').filter(x=>x==='BEGIN:VEVENT').length,1,'Notes cannot inject calendar components');
assert.ok(ics.includes('DTEND;VALUE=DATE:20270101'));
assert.ok(ics.split('\r\n').every(line=>Buffer.byteLength(line,'utf8')<=75),'UTF-8 line folding');
assert.doesNotMatch(ics,/ATTENDEE|ORGANIZER|BEGIN:VALARM/);
console.log('PASS optional reflection export; no query tokens, network, analytics or persistence; details only');
